### ISSUE TITLE
Dish animate module name Typo

### ISSUE THREAD

**Issue by SpannerMonkey** [GER-Space/Kerbal-Konstructs#101]
Re namespace = KerbalKonstructs
               name = DishAnimate

Hi was setting up a new item and was confounded as to why it failed,  my eyes read RotationTrasform as RotationTransform. hence rotation transform not found. 
As it looks as though KK needs a tweak for KSP 1.4.4 could you fix this minor thing.  

https://github.com/GER-Space/Kerbal-Konstructs/blob/135d4cc20ce11018b0a633ee0d153b39574835b0/src/Core/StaticObjects/StaticModules/DishAnimate/DishAnimate.cs#L12

**Comment by GER-Space** [comment]
Oh thanks, I never saw it and everyone that tested it used my configs... 
I will release a new version in a few hours, I hope KSP 1.4.4 doesn't break too much.
