### ISSUE TITLE
kerbal konstructs no supported modules found! HELP ME PLZ!

### ISSUE THREAD

**Issue by tonimark** [GER-Space/Kerbal-Konstructs#105]
![20180703233900_1](https://user-images.githubusercontent.com/17166550/42243522-56203242-7f1a-11e8-8e60-2cf2ff786f04.jpg)

**Comment by GER-Space** [comment]
This is the KAS menu, not kk. 
Sadly Kas uses the same key config to open It's menu, but it can be changed in the Kas menu.

**Comment by tonimark** [comment]
where is the kas menu

**Comment by GER-Space** [comment]
This was an issie with KSP 1.4.4. fixed with KSP 1.4.5
