### ISSUE TITLE
"Null reference exception" log output when accessing the "research" facility GUI.

### ISSUE THREAD

**Issue by Mechfan** [GER-Space/Kerbal-Konstructs#108]
When opening the GUI for any konstruct set as a "research" facility, the GUI opens, but just as a flat grey screen, and the log exports this repeatedly: 

[EXC 04:05:25.240] NullReferenceException: Object reference not set to an instance of an object
	KerbalKonstructs.UI.ProductionGUI.ProductionInterface (KerbalKonstructs.Core.StaticInstance selectedFacility, System.String facilityType)
	KerbalKonstructs.UI.FacilityManager.drawFacilityManagerWindow (Int32 windowID)
	UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, Int32 instanceID, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)

**Comment by GER-Space** [comment]
fixed with:
https://github.com/GER-Space/Kerbal-Konstructs/commit/2d05c5f7cc3a6ccdf51d5ed653506334546b25dd
