### ISSUE TITLE
Issue with launch site selection Kerbal-Konstructs-1.3.9.14

### ISSUE THREAD

**Issue by SpannerMonkey** [GER-Space/Kerbal-Konstructs#109]
Issue with launch site selection 
Kerbal-Konstructs-1.3.9.14
KSP1.4.5
Small test install only. (debugging carrier deck) 

Launch selector is fully operational.  selecting launch site using the proper method results in the expected on screen messages. Cofirming that launch site is selected .   However on launch the craft is loaded  to the runway.  Return to SPH to confirm that launch site is properly selected, it is ,   re launch craft is once again spawned to runway.

Reverted to previous KK dll and launch site function is as expected , craft spawn at chosen launch site

**Comment by GER-Space** [comment]
This version is for ksp 1.3.1
