### ISSUE TITLE
Version 1.4.5.3 has wrong data in the .version file

### ISSUE THREAD

**Issue by linuxgurugamer** [GER-Space/Kerbal-Konstructs#110]
Version file has this:
	{
		"MAJOR":1,
		"MINOR":4,
		"PATCH":5,
		"BUILD":2
	},

So AVC and CKAN are confused (so was I)

**Comment by GER-Space** [comment]
oopsi, 
That comes from releasing test versions... 
I will fix that later.

**Comment by linuxgurugamer** [comment]
Just a suggestion:  I did this a number of times in my mods, I avoid it now by having my build process generate the file name from the version file.  So, after doing a build, I can instantly see that I forgot to update the number.

**Comment by GER-Space** [comment]
I extract it from the assembly version, But I will update the build script to write the version file aswell.
