### ISSUE TITLE
can't store vessels in hangar

### ISSUE THREAD

**Issue by tonimark** [GER-Space/Kerbal-Konstructs#112]
where i push my aircraft near the facility it say that is still far away and i am unable to store it:
![20180822141913_1](https://user-images.githubusercontent.com/17166550/44462251-b6bdfe80-a61c-11e8-8411-8f8209adc2c3.jpg)

**Comment by griderd** [comment]
I looked at the source code, and from what I can tell, your vessel must NOT contain crew and must NOT be the active vessel. If you disembark your Kerbal(s), you can store the vehicle once they're on the ground from EVA mode.

**Comment by tonimark** [comment]
ok thanks
