### ISSUE TITLE
Model-Texture Switching 

### ISSUE THREAD

**Issue by GER-Space** [GER-Space/Kerbal-Konstructs#117]
Allow variants of one Model. (advanced textures?)

**Comment by omega482** [comment]
Been having thoughts about the implementation of this one. I think using a similar system to the stock variants system would work well.

Stock mesh switching works by simply toggling on and off gameobjects defined in the CFG. All the variants are stored in the same .mu See below:

`MODULE
	{
		name = ModulePartVariants
		baseVariant = TypeA
		VARIANT
		{
			name = TypeA
			displayName =  TypeA
			primaryColor = #ACA79FFF
			secondaryColor = #605F5CFF
			
			GAMEOBJECTS
			{
				SteelCrateA = true
				SteelCrateB = false
				SteelCrateC = false

			}

		}
		VARIANT
		{
			name = TypeB
			displayName =  TypeB
			primaryColor = #ACA79FFF
			secondaryColor = #605F5CFF
			
			GAMEOBJECTS
			{
				SteelCrateA = false
				SteelCrateB = true
				SteelCrateC = false

			}
		}
				VARIANT
		{
			name = TypeC
			displayName =  TypeC
			primaryColor = #ACA79FFF
			secondaryColor = #605F5CFF
			
			GAMEOBJECTS
			{
				SteelCrateA = false
				SteelCrateB = false
				SteelCrateC = true

			}

		}
	}`

So all a static creator would have to do is to export all the mesh variants in the same mu. Then they simply decide which game objects should be present for the variants in the cfg. KK would have to store a variant classifier in the instance file. UI elements could be a simple "next variant" button and the variant name.

**Comment by GER-Space** [comment]
This sounds reasonable. I only need to descide what to do with Mudules like Texture Switching an AnimateOnSunrise, OnClick etc... But I think I have an idea..
I need to separate the Instance GameObject from the Mesh GameObject. (currently its the same)
That way I can also easier implement the destruction of buildings. 
All StaticModules end up inside the Base GameObject and I can despawn and Spawn the Mesh at will (I i only need to call some modules to redo thier work) and setup destruction Objects again...

**Comment by GER-Space** [comment]
Planned features: 


```
MODEL {
bla 
bla 
bla
  VARIANT 
   {
    Name = AllBetter              //manditory
    NewMeshName = allGreaterMesh      //optional
    DeactiateTransforms = this, that   // optional:  list of transforms that get deactivated 
    ActiateTransforms = this, that   // optional:  list of transforms that get activated 
    TextureSet 
    {
          Transforms = this, that   // list of transforms to alter
          // at least one of the below
           Color = #605F5CFF   //new color value
          Texture = newexture  // replace the texture
   }
    TextureSet 
    {
          Transforms = this, that   // list of transforms to alter
          // at least one of the below
           Color = #0000000   //new color value
          Texture = newexture  // replace the texture
   }
   }

  VARIANT
  {
.....
  }

}
```

**Comment by theonegalen** [comment]
Is the config the same as what you posted earlier?

Also, woohoo!
