### ISSUE TITLE
Issue with loading crafts

### ISSUE THREAD

**Issue by Toonu** [GER-Space/Kerbal-Konstructs#119]
When loaded save file, and went into one of crafts/spawn new one, all other crafts spawned above/under ground and were thus destroyed. Video and log showing it included. People from BDA forum topic suggested it can be due to BDA Physics range extender don't count KK surfaces as surfaces and loads crafts underground.

Video: https://youtu.be/bMwHrzyrhj4
[KSP (1).log](https://github.com/GER-Space/Kerbal-Konstructs/files/2468273/KSP.1.log)

**Comment by GER-Space** [comment]
I tried to implement a new base loading code, now the bases are loaded outside the vessel load range. If that will not help, I must make this configurable through a setting menu

**Comment by Toonu** [comment]
Great, will try it and let you know. Thanks a lot for you efforts!

**Comment by GER-Space** [comment]
is it now working as indendent?

**Comment by Toonu** [comment]
I am sorry, got some bad illness and couldn't try. Will inform you once I do. ;)

**Comment by GER-Space** [comment]
Should be fixed
