### ISSUE TITLE
VisibilityRange in configuration files ignored

### ISSUE THREAD

**Issue by meltingSnowdrift** [GER-Space/Kerbal-Konstructs#130]
The "VisibilityRange" value in instance list cfg files appears to have no effect. Regardless of these values, models load and become unloaded at approximately 40km from the active vessel.

This problem was discovered when I tried to increase model loading ranges to create compatibility with Physics Range Extender by making Kerbal Konstructs models load at longer ranges than vessels to prevent vessels from falling to the ground before the KK models they rest on become loaded.

**Comment by GER-Space** [comment]
KK should now automatically adjust the loading range to the Physics Range (+ some extra KM)

I use this as a reference.  + 1.5* the localgrouprange which is currently 25KM. 
`PhysicsGlobals.Instance.VesselRangesDefault.flying.load`

I don't know which parameter you change, maybe I poll the wrong one.

**Comment by GER-Space** [comment]
On a sencond thought, querrying the flying distance might not the best choice, as most objects on structures are on the landed state.

**Comment by meltingSnowdrift** [comment]
> KK should now automatically adjust the loading range to the Physics Range (+ some extra KM)

At least in the presence of Physics Range Extender, this does not occur correctly. Regardless of settings in Physics Range Extender, KK loading distance seems to be around 40km. Also, what is meant by "flying distance"?

In addition to specifically resolving this issue, can you please make loading distances overridable by the user, preferably in the KK instance editor, so that we can manually work around these kinds of problems regardless of the particular case?

**Comment by GER-Space** [comment]
new Release is out with the bugfix for it:

https://github.com/GER-Space/Kerbal-Konstructs/releases/tag/1.4.5.47
