### ISSUE TITLE
Kerbal Konstructs 1.4.5.53 apparently fails to load with GPP

### ISSUE THREAD

**Issue by chwthewke** [GER-Space/Kerbal-Konstructs#132]
Hello

When using Kerbal Konstructs 1.4.5.53 with (more than a hundred other mods, including) Galileo's Planet Pack, all I get upon entering the KSC scene is the default space center (plus one single extra launchpad near the monolith, for some reason). I would expect to have many more konstructs including an extra runway, etc., as was the case just prior to upgrading KK.

I'm attaching output_log.txt and KSP.log, where the relevant bit seems to be:
```
[EXC 06:24:53.676] NullReferenceException
	KerbalKonstructs.Core.InstanceUtil.MangleSquadStatic (KerbalKonstructs.Core.StaticInstance instance)
	KerbalKonstructs.Core.StaticInstance.Spawn ()
	KerbalKonstructs.Core.StaticInstance.TrySpawn ()
	KerbalKonstructs.Core.LaunchSiteManager.CreateLaunchSite (KerbalKonstructs.Core.StaticInstance instance, .ConfigNode cfgNode)
	KerbalKonstructs.Core.LaunchSiteManager.AttachLaunchSite (KerbalKonstructs.Core.StaticInstance instance, .ConfigNode instanceNode)
	KerbalKonstructs.KerbalKonstructs.LoadInstances (.UrlConfig configurl, KerbalKonstructs.Core.StaticModel model)
	KerbalKonstructs.KerbalKonstructs.LoadModelInstances ()
	KerbalKonstructs.KerbalKonstructs.Start ()
```
[ksp_logs.zip](https://github.com/GER-Space/Kerbal-Konstructs/files/2785882/ksp_logs.zip)

Thank you!

**Comment by GER-Space** [comment]
Can you please test this release? 
https://github.com/GER-Space/Kerbal-Konstructs/releases/tag/1.4.5.55

**Comment by chwthewke** [comment]
With 1.4.5.55, I see no exception, but no Konstructs in KSC either, unfortunately.

Keeping on 1.4.5.52 at the moment.

Thank you for your time

**Comment by chwthewke** [comment]
Sorry, that previous comment might have been a bit hasty...

A bit of further testing revealed:
- A clean install with only KK 1.4.5.55 and GPP (+ its hard deps) seems to work fine. The space center scene at least looks just as expected, all the extra buildings, etc.
- Now I've reverted my main game to KK 1.4.5.52 and poof, no buildings, even if I start a new save, so it may be that we just happened to mess up my install, between CKAN and I ^^

**Comment by chwthewke** [comment]
Ok, sorry about the delay, this game takes forever to load with all those mods 😅 

After a bit of fiddling (force-reinstalled KK 1.4.5.54 in CKAN, then force-reinstalled GPP, *then* overwrote KK with .55), everything is OK in KSC! 💯
