### ISSUE TITLE
No new bases / button for building bases

### ISSUE THREAD

**Issue by fruitsbar** [GER-Space/Kerbal-Konstructs#135]
Can't see any new bases. And it ALWAYS says that KSC is the nearest base. The only stuff I have is the KK tool in the Toolbar which only shows 'Start air racing!' and 'Basic Orbital Data'.

**Comment by fruitsbar** [comment]
![image](https://user-images.githubusercontent.com/49098132/55277568-a4661a80-52f9-11e9-8084-b25bf68fec36.png)
here's a screenshot.

**Comment by GER-Space** [comment]
you need to press ctrl + k to open the editor

**Comment by fruitsbar** [comment]
thanks! making my own bases already.
