### ISSUE TITLE
Many objects deleted upon updating to version 1.4.5.64

### ISSUE THREAD

**Issue by meltingSnowdrift** [GER-Space/Kerbal-Konstructs#137]
Upon launching KSP after installing this update using CKAN, most of the objects of one of my bases disappeared. The lost objects include a stock KSC runway and various objects from the Kerbinside assets collection.

At least some, and probably all, of the affected instances appear to still exist in instance list files. These instances do not show up in the list of the in-game editor. Vessels previously landed on top of them fall through the now empty space to the ground.

An example of a file specifying a disappeared instance is below.

```
// Generated by Kerbal Konstructs

STATIC
{
	pointername = KSC_Runway_level_2
	Instances
	{
		UUID = 7d2b35a5-cf3f-4bf2-b3c2-8d6f42362a02
		CelestialBody = Kerbin
		RelativePosition = 1023.55664,8.65130615,13.7614746
		Orientation = 0.0977289453,88.8319626,-0.000687071879
		isScanable = False
		ModelScale = 1
		//old
			//VisibilityRange = 25000
		//new
			VisibilityRange = 100000
		Group = COLE
		GrasColor = 0.0809368193,0.112854056,0.0504357405,-0.0624183156
		LaunchSite
		{
			FacilityType = KKLaunchSite
			OpenCost = 0
			CloseValue = 0
			FacilityName = 
			LaunchPadTransform = End09/SpawnPoint
			LaunchSiteName = COLE
			LaunchSiteAuthor = Squad
			LaunchSiteType = Any
			LaunchSiteLength = 0
			LaunchSiteWidth = 0
			LaunchSiteHeight = 0
			MaxCraftMass = 0
			MaxCraftParts = 0
			InitialCameraRotation = 90
			LaunchSiteIsHidden = False
			ILSIsActive = False
			OpenCloseState = Closed
			Category = Runway
		}
	}
}
```

**Comment by GER-Space** [comment]
cannot reproduce the issue, maybe it was CKAN deleting the newinstances folder.
