### ISSUE TITLE
launchsites disappearing

### ISSUE THREAD

**Issue by Cdough8** [GER-Space/Kerbal-Konstructs#142]
I am currently running KSP 1.2.2 and I know it is an old version but I have some other mods that run only in that version. I spawn a vehicle on a runway I created and all of the statics are also spawned with it. I then go back to space center and spawn another vehicle at the same base but all of the statics disappear. The colliders are still on but everything is invisible. When I recover the vehicle I spawn and switch to the original vehicle at the base all of the statics reappear. Any help?

**Comment by GER-Space** [comment]
Sorry, I cannot go back and fix 1.2.2. KSP had too many changes since 1.4, so I had to give up to backport everything. At one point I just had to move on.
