### ISSUE TITLE
Reconsider storing new instances data in .cfg 

### ISSUE THREAD

**Issue by whale2** [GER-Space/Kerbal-Konstructs#144]
Every time a new instance created or old one updated, Module Manager picks up .cfg file and rebuilds its cache. I don't see why one might want to edit instance data with MM patches, maybe store them not in .cfg?

**Comment by histalonia** [comment]
I for one much prefer these on disk.  They are portable and editable.

**Comment by GER-Space** [comment]
I need the files pared in the ConfigNode format. this I can only get with .cfg files, because I don't know where they are. Scanning everything is nothing I want to do.
Damon and Omega actually use MM patches quite extensivle for thier statics.
