### ISSUE TITLE
Exported groups/bases load with psuedo random rotations

### ISSUE THREAD

**Issue by histalonia** [GER-Space/Kerbal-Konstructs#145]
In KSP 1.7.3 with KK 1.7.0.3 exported groups are loading with a pseudo random rotation.
The group saves with a rotation of 0 but loads as 312.

Also there is no way to export in the old format, so every time you load the Group and airfield it rotates wrong.  Fixing and resaving doesn't help the next time you start KSP.

Here is the problem group of mine.  I deleted the original NewInstances, and kept the exports so it seems all the work is lost.  Not even the old version of KK will load the group with the new lat lon info.
[Zagonia.zip](https://github.com/GER-Space/Kerbal-Konstructs/files/3479553/Zagonia.zip)

And I have tried this without OSSNTR with just the air strip.  
I went back to module manager 3.1.3 as well, but still the same issue.

**Comment by GER-Space** [comment]
this got hopefully fixed in the 1.8.1 release of KK.
