### ISSUE TITLE
trigger recovery of landed vesssels within hangar collider

### ISSUE THREAD

**Issue by GER-Space** [GER-Space/Kerbal-Konstructs#15]
As per : http://forum.kerbalspaceprogram.com/index.php?/topic/94863-112-kerbal-konstructs-v0971-slopey-glidey/&page=20#comment-2524603

**Comment by GER-Space** [comment]
this could be done when remodeling the hangar objects and with a recovery module, which listens to the recovery collider

**Comment by Ruedii** [comment]
Also, adding the area in front of the hangers (the taxiway) to the list of full retrieval value locations would be nice.

**Comment by GER-Space** [comment]
Hangars are reworked, trigger actions too... What is missing is the combination of both, but that's only cfg magic.
I do not remodel things, so it's done
