### ISSUE TITLE
Ctrl + k opens interface but buttons do nothing

### ISSUE THREAD

**Issue by MonsterViper5** [GER-Space/Kerbal-Konstructs#175]
I press ctrl + k and the interface comes up but the buttons don’t function. I found a ctrl + l which brings up another smaller menu and I can open the instance list yet it doesn’t do any thing. I’ve checked the dependants, I have a crewed craft and have tried to look for different versions and can’t find anything else to check. I have Waterfall, Kerbal Engineer, Better time warp, and obviously Kerbal Konstructs. I had advanced tweakables and editor extensions redux. 

Is there anything that I can do to get it to work.

**Comment by Noisydocter** [comment]
Im having the same issue now, did you find a fix?

**Comment by BravoAlpha101st** [comment]
i have the same issue too

**Comment by MonsterViper5** [comment]
Still don’t have a fix sorry. I tried it recently with all my updated mods and module managers and still no effect.

**Comment by sp22222222** [comment]
same problem here

**Comment by sp22222222** [comment]
i did some digging and found the issue, download these .ZIPs and put them in GameData;
https://github.com/KSP-RO/Kerbal-Konstructs/releases/tag/v1.8.6.0 
https://github.com/KSP-RO/CustomPreLaunchChecks/releases/tag/1.8.1.1

**Comment by MonsterViper5** [comment]
Thanks, I'll see if it works

**Comment by BravoAlpha101st** [comment]
> Thanks, I'll see if it works

Did it fix it?

**Comment by MonsterViper5** [comment]
Haven't had the chance to try yet.

**Comment by BravoAlpha101st** [comment]
K, I might try it soon too

**Comment by BravoAlpha101st** [comment]
Woah just realised that's Realism Overhaul, might not work if we don't have it

**Comment by MonsterViper5** [comment]
It worked.

Thanks
