### ISSUE TITLE
KK not working with RSS on 1.2.2

### ISSUE THREAD

**Issue by billgarlic** [GER-Space/Kerbal-Konstructs#37]
There was a bug back in December that is reported as fixed but here is a report on an issue I found yesterday:

I have a clean install of 1.2.2.  I installed RealSolarSystem via CKAN (so it gets the dependencies) and manually installed the latest KK and KSC Floodlights.  They do not appear.  When I attempt to use Ctrl-K in the launch view (trying to find them to re position them), nothing appears.  The mod window itself on the main screen does come up, but Ctrl-K does not work there either.  

I removed the RSS directories and dependencies without changing anything else and KK works fine.  I can go to the launch view and hit Ctrl-K and am able to move the Floodlight towers around.  

So the only thing in place causing the failure is the core RSS needs which includes:
Real Solar System 12.0.0
Module Manager 2.7.6
Kopernicus 1.2.2-5
Modular Flight Integrator 1.2.4.0
Textures (8192 size)

No other mods installed.

**Comment by GER-Space** [comment]
I'll have a look. at least the editor should open, and GPP is working fine (I think), or Gallilio be more upset

**Comment by GER-Space** [comment]
I found the source of the problem and fixed it. 

KK will die if no statics are initialized. 

You can use this version: https://github.com/GER-Space/Kerbal-Konstructs/releases/tag/0.9.8.9 

until I release a new Beta, or manually edit a configFile of some Statics and replace the 
"CelestialBody = Kerbin"
with "CelestialBody = Earth"
or "CelestialBody = HomeWorld" (which is true)

**Comment by GER-Space** [comment]
I have a new Verison which contains the real bugfix:
https://github.com/GER-Space/Kerbal-Konstructs/releases/tag/0.9.9.9

**Comment by billgarlic** [comment]
Things appear to be working with he latest 0.9.9.9c build.  I believe you can close this bug.  Thanks for your help.
