### ISSUE TITLE
Create NavUtilities config for all runways on save

### ISSUE THREAD

**Issue by GER-Space** [GER-Space/Kerbal-Konstructs#38]

**Comment by whale2** [comment]
Is it supposed to be NavUtilities? I can pick this up, if you'd like.

**Comment by GER-Space** [comment]
Yes I'm tired and shoud to go to bed. 

If you could do this, this would be great. You should renew you KK sources, as I changed a lot in the last few days. (StaticObject is now named StaticInstance) and the old configparser with (get-settings,set-settings) is gone.

**Comment by GER-Space** [comment]
My idea was to use the LaunchSites transform position as the LandingPoint, You can access the transform-name from the LaunchSite class and search the gameObject for the transform object.

**Comment by GER-Space** [comment]
@whale2 
this is now merged

**Comment by GER-Space** [comment]
this is resolved as KK now got its official release.
