### ISSUE TITLE
Compatibility issues with KSP Interstellar Extended

### ISSUE THREAD

**Issue by ShakenU** [GER-Space/Kerbal-Konstructs#49]
Opened an issue with them as well, but game crashes right after main loading screen, just before the main menu. Fresh install of the game. 
Mod installed directly from a fresh clone of the git repo. 

[buildID64.txt](https://github.com/GER-Space/Kerbal-Konstructs/files/1464109/buildID64.txt)
[error.log](https://github.com/GER-Space/Kerbal-Konstructs/files/1464106/error.log)
[output_log.txt](https://github.com/GER-Space/Kerbal-Konstructs/files/1464107/output_log.txt)

**Comment by GER-Space** [comment]
this is a crash from within the KSP settings menu loader. As I can see it the KK menue settings got loaded normally. After that a diffrent settings bar called PM loaded and then a crash occured.
