### ISSUE TITLE
Add RemoteTech & CommNet support

### ISSUE THREAD

**Issue by GER-Space** [GER-Space/Kerbal-Konstructs#5]
The Groundstations could be used as RemoteTech&CommNet groundstations. 

perhaps also with a limited range around bases (60 km for runnway and 30 for pads)

**Comment by antonioltg91** [comment]
I'm going crazy adding the traking stations by hand in the RT config, this feature will be in next update?

**Comment by GER-Space** [comment]
I you can wait 2 or 3 weeks, then I think I'll have the feature implemented in some way or an other. (I think I use the range-Values of the tracking stations, or with some multiplier) 
First I need finish my ongoing work on the editor, which is currently pretty broken in my builds.

**Comment by antonioltg91** [comment]
Ok the problem is TarsierSpaceTech, I don't know what is the problem in particular.
But I still have only Kerbin and the Mun available 
Here is the full log http://antonioltg.com/ksp/KSP2.log

**Comment by GER-Space** [comment]
You have ResearchBodies installed (which masks all planets except Kerbin and Mun) but this is KerbalKonstructs github, I cannot even find that you have KK installed....

**Comment by antonioltg91** [comment]
oops wrong github sorry

**Comment by GER-Space** [comment]
@antonioltg91 I made a new Release, which added basc support for RT and CommNet GroundStations.

**Comment by antonioltg91** [comment]
I currently not use this mod anymore, does it works on world different from kerbin?

**Comment by GER-Space** [comment]
yes.
