### ISSUE TITLE
Office funds generation too fast when focused

### ISSUE THREAD

**Issue by xilexio** [GER-Space/Kerbal-Konstructs#50]
When the window with office building is open the funds generate insanely fast, regardless of time acceleration (around 10000 funds/second when fully staffed, or a few thousand/second with a few kerbals). This makes it impossible to use offices in a non-cheaty way.

**Comment by xilexio** [comment]
I had a look at the code and I think there must be a problem in this general area:
[https://github.com/GER-Space/Kerbal-Konstructs/blob/1e87ef0741f746e894369ae70a06ba9aba2f79c8/src/Facilities/ProductionGUI.cs#L156-L175](https://github.com/GER-Space/Kerbal-Konstructs/blob/1e87ef0741f746e894369ae70a06ba9aba2f79c8/src/Facilities/ProductionGUI.cs#L156-L175)
I think there is a bug with time being incorrectly counted when the updates happen too fast. I was expecting something like rounding errors that lead to adding ceil(small float number), but it seems floats are being used. The updating code in the if in L156 looks okay to me though, I'd have to actually compile it to be sure.

**Comment by xilexio** [comment]
Actually, how about never updating it, just saving the time when the funds were taken last time and just displaying a computed min(maxFunds, days * ratio) every time? That way, the intermediate state would never be there, and you'd only have to save a single value - time of last withdrawal. That would remove any bug connected to updating funds too often instead of computing them and updating at the point of withdrawal only.

**Comment by GER-Space** [comment]
The main problem was. that I pulled the productionrate and set it to the last-check time. And I did it every frame... that why you got the insane amounts of credits and research.

**Comment by GER-Space** [comment]
ok, the Code is really a mess. I never really looked into it. I always only made it compile... this time I'm fixing it for real and I will give it reasonable numbers for the investment.

**Comment by GER-Space** [comment]
fixed with commit 3fbdf96459af856f96eab5538f0878f63465378f
