### ISSUE TITLE
Duplicate facilities in manager

### ISSUE THREAD

**Issue by xilexio** [GER-Space/Kerbal-Konstructs#51]
Very often the same facilities appear twice on the list of operational facilities. However, correct facility is shown/updated when opening it, so it's not game-breaking, just confusing.

**Comment by GER-Space** [comment]
Thanks for report, I'll have a look intobit

**Comment by GER-Space** [comment]
can you please tell me where this happens? I only see the facilities once.

**Comment by xilexio** [comment]
Found an easy way to reproduce it. After opening the KK menu and being close enough to a base, can show/hide a list of facilities. Each time you click that, new elements seem to be added to the list without clearing the old ones, duplicating facilities and even leaving the unloaded (but visited before going to space center) ones on the list. Do you want a few screenshots?

**Comment by GER-Space** [comment]
Thanks, now I found the offending Code... one line was missing. I'll fix it with the next release. A prerelease might follow later tonight. 
I never resetted the list cached facilities when I scan for new ones. (I do the scan when the button is pressed)
