### ISSUE TITLE
Some bases are right next to each other

### ISSUE THREAD

**Issue by xilexio** [GER-Space/Kerbal-Konstructs#52]
Some bases are next to each other instead of being a single base, e.g., bio-dome and research stations at north pole. They can share facilities and need to be bought separately. It's weird considering it's impossible to create a new base within 100km of another.

**Comment by GER-Space** [comment]
This is more a Kerbin-side bug than kk, but I'll have a look

**Comment by GER-Space** [comment]
This is because Bio-Dome is its own launchsite. (a heli bad on top of the dome) Maybe the 100km limitation should go from KK.

**Comment by GER-Space** [comment]
there was never a true 100km limitation. but the message is finally gone.
