### ISSUE TITLE
StaticObjectUpdate is called twice as often as the Update method

### ISSUE THREAD

**Issue by Li0n-0** [GER-Space/Kerbal-Konstructs#54]
In KK 1.2.0.1 with KSP 1.3.1 StaticObjectUpdate is called twice as often as the Update method. (same with KK 1.2.0.0 and KSP 1.3.0) 

![](https://i.imgur.com/wfnmpjT.png)
One "Debug.Log" for Update and one for StaticObjectUpdate. 

#53  is related, I made it so StaticModule can stop their logic while StaticObjectUpdate act crazy. Didn't understand it was a bug at the time.

Report originally made [here](https://forum.kerbalspaceprogram.com/index.php?/topic/151818-131-kerbal-konstructs-131-07102017/&do=findComment&comment=3283208)

**Comment by GER-Space** [comment]
if was called every frame, not twice for an Update(), because some braces have been missing after a if() clause. That way the value was changed only if the toggle was changed, but the object was updaes every time the editor window was drawn.

**Comment by GER-Space** [comment]
I'll merge #53 nevertheless, because it is still usefull.
