### ISSUE TITLE
AnimateOnClick could not be loaded

### ISSUE THREAD

**Issue by Li0n-0** [GER-Space/Kerbal-Konstructs#59]
I got this message in the console, on the main menu : 
`KK: Module AnimateOnClick could not be loaded in KSCFloodlight/FloodlightKSC(Clone)`

And when at the KSC : 
```
NullReferenceException: Object reference not set to an instance of an object
  at KerbalKonstructs.AnimateOnClick.Start () [0x00000] in <filename unknown>:0 
```

I've tested with another static and got the same result. The animations are correctly set. They work with AnimateOnClick on previous KK version and with my StaticLight module on KK 1.2.9.0

**Comment by GER-Space** [comment]
Uhm this might be a problem with the StaticInstance being inherited at initialization change. 
Thanks for the report, I'll dig into it

**Comment by GER-Space** [comment]
found it: AniMateOnClick was not inherited from StaticModule, but from plain Monobehavior. I'll publish a new release in a few minutes
