### ISSUE TITLE
Broken most functionalities in 1.3.0.1 with other mods

### ISSUE THREAD

**Issue by xilexio** [GER-Space/Kerbal-Konstructs#66]
It seems 1.3.0.0 and 1.3.0.1 are broken for me with KSP 1.3.1 x64 (windows), Kerbin Side complete 1.4, Kerbal Construction Time 1.3.0.43 (dev ver), ResearchBodies 1.9.6, Kerbin Side GAP 2.3, and over 100 of other mods. Reverting KK back to 1.2.0.4 fixes everything.

The problem is that in Space Center view buildings appear, but in the actual game they do not. List of facilities around KSP when clicking KK button is also empty. I am unable to launch new vehicles from Space Center from VAB or SPH using Kerbal Construction Time menu, since clicking "Launch" does not do anything (though it probably just needs a KCT update).

Working version with KK 1.2.0.4 - view on KSC when "flying" a flag:
![image](https://user-images.githubusercontent.com/603874/37175015-82172350-2318-11e8-9506-3dda0a328e42.png)
Logs when stuff was working correctly on 1.2.0.4
[KSP-1.2.0.4.log](https://github.com/GER-Space/Kerbal-Konstructs/files/1794710/KSP-1.2.0.4.log)
The additional building next to R&D is an observatory from ResearchBodies, not KK.

Now with KK 1.3.0.1:
1. View in Space Center displays everything correctly:
![image](https://user-images.githubusercontent.com/603874/37175289-63873b68-2319-11e8-99d1-499022ec4a0a.png)

2. "Flying" a flag in KSC:
![image](https://user-images.githubusercontent.com/603874/37175381-a7579356-2319-11e8-931f-89bef2b20478.png)
* Facilities are not displayed
* I clicked on NGS to KSC, got "NGS set to KSC", but you can see "NGS: NO TARGET" in KK's flight assistant
* Show/Hide of operational facilities doesn't do anything (so my guess is that it's not just facilities being invisible)

3. Problem with Kerbal Construction Time after upgrading from 1.2.0.4:
![image](https://user-images.githubusercontent.com/603874/37175685-91aa2cfc-231a-11e8-89e2-27152681e917.png)
* Clicking on "Select LaunchSite" does not display a list of launch sites. Was the API modified?
* Clicking on "Launch" does not launch the vehicle, even though it's supposed to be from KSC's launchpad.

4. Logs:
[KSP-1.3.0.1.log](https://github.com/GER-Space/Kerbal-Konstructs/files/1794775/KSP-1.3.0.1.log)

**Comment by GER-Space** [comment]
About KCT I cannot help. 
Your other bug is amaizing, as Its not possible for KerbalKonstricts to determin your position. No Active Vessel, no camera position, nothing... I have no idea how that could happen.

**Comment by GER-Space** [comment]
can you please try this release? 
https://github.com/GER-Space/Kerbal-Konstructs/releases/tag/1.3.0.2

**Comment by xilexio** [comment]
Facilities and landing guides seem to be working:
![image](https://user-images.githubusercontent.com/603874/37184200-5a35fda8-233a-11e8-939c-53524811c0be.png)

KCT stuff still does not work, as expected, so I can't test if launching new vehicles work under my mod configuration.

Also, I got a bunch of errors that did not seem to cause trouble, e.g.:
`[ERR 01:34:48.120] KK: Facility Index Missmatch in fac: BlackKrags_ksidefueltank3_0
[ERR 01:34:48.120] KK: Facility Index Missmatch in fac: CoalerCrater_ksidetanks13_0`

You said you don't need logs, but it doesn't hurt to upload them anyways:
[KSP.log](https://github.com/GER-Space/Kerbal-Konstructs/files/1795247/KSP.log)

I guess I'll use 1.2.0.4 while waiting on KCT to update, since it is rather behind on releases.

**Comment by GER-Space** [comment]
The facility mismatch errors are harmless, because I changed the full tanks ( internally they are now a different type of facility.)
KCT: I don't know what api calls they use. I must check this mod tomorrow.

**Comment by GER-Space** [comment]
OK I found it... They access an internal structure that I now reworked. I must bring back the old Name and document it that it's needed for KCT, Because KCT development is pretty dead.

**Comment by GER-Space** [comment]
I think I repaired KCT integration
https://github.com/GER-Space/Kerbal-Konstructs/releases/tag/1.3.0.3

**Comment by GER-Space** [comment]
I checked it on my own. KTC is working again with 1.3.0.3. Thank you for your report.
