### ISSUE TITLE
The landing guide is displayed when focused on a facility

### ISSUE THREAD

**Issue by xilexio** [GER-Space/Kerbal-Konstructs#69]
A landing guide is displayed in the middle of the screen even if focusing on a facility ("flying" a flag in the middle of KSC below):
![image](https://user-images.githubusercontent.com/603874/37243817-e3cb333a-247f-11e8-80be-c69ac9931f4d.png)
![image](https://user-images.githubusercontent.com/603874/37243829-089957aa-2480-11e8-90e0-8c9419a52dfc.png)

Adding this minor issue only for completeness. It doesn't break anything.

**Comment by GER-Space** [comment]
This are the reference lines. bit the normal landing guide. It was always like that. I don't know if they should look like that or not.

**Comment by xilexio** [comment]
Oh, I do not mean that the reference lines being there is a bug by itself. It's just that they also appear when clicking on a facility name. Then the camera focuses on the facility instead of on the active vessel, but reference lines remain.

**Comment by GER-Space** [comment]
This is directly painted onto the screen, as long you have the landing guides activated. You can turn them off anytime.

**Comment by xilexio** [comment]
I noticed that sometimes additional white lines appear around landing guides:
![image](https://user-images.githubusercontent.com/603874/37245139-1eb89bae-2494-11e8-8c5b-658922e9ecaf.png)
(sometimes when facing the craft from the side they appear in pretty random places too)

Also, when I used landing guides when taking off, I saw them render off in distance in front of me (KSC was behind):
![image](https://user-images.githubusercontent.com/603874/37245168-8f60e42e-2494-11e8-9d5f-6dd4138919b7.png)
The additional landing guides in the front remained until all landing guides disappeared.

**Comment by xilexio** [comment]
An example of that weird line when facing away from an airport:
![image](https://user-images.githubusercontent.com/603874/37245984-3216a4f4-24a1-11e8-93ce-cc8c60124fb3.png)

**Comment by GER-Space** [comment]
I think I know what the white lines are,,, the should show the direct path to the runway, but they are broken. 
I will need to rework this at one point. I never really looked at this parts of the code. 
This is all Post 1.4 stuff, as its not really important.

**Comment by GER-Space** [comment]
you should see a improved version in the next release. It need some more testing on my side.

**Comment by GER-Space** [comment]
I reworked the landing guides. 
https://github.com/GER-Space/Kerbal-Konstructs/releases/tag/1.3.0.8
