### ISSUE TITLE
NGS: NO TARGET displayed after setting a target

### ISSUE THREAD

**Issue by xilexio** [GER-Space/Kerbal-Konstructs#70]
"NGS: NO TARGET" is displayed in the NGS window after selecting a target launch site, e.g., after selecting VAB helipad as shown below:
![image](https://user-images.githubusercontent.com/603874/37243935-c3dbb1c4-2481-11e8-8946-dbeda3b09a62.png)

Logs: 
[KSP.log](https://github.com/GER-Space/Kerbal-Konstructs/files/1799518/KSP.log)

**Comment by GER-Space** [comment]
I think its the same problem I had with the default launchSites not set. 
I post a new  prerelease soon.

**Comment by GER-Space** [comment]
LaunchSites allways returned true when check to == null

**Comment by GER-Space** [comment]
https://github.com/GER-Space/Kerbal-Konstructs/releases/tag/1.3.0.5

**Comment by xilexio** [comment]
It works now.
