### ISSUE TITLE
Possible to select closed launch site as the default launch site

### ISSUE THREAD

**Issue by xilexio** [GER-Space/Kerbal-Konstructs#71]
It is possible to select a closed launch site as the default launch site:
![image](https://user-images.githubusercontent.com/603874/37245354-f15cb03e-2496-11e8-92d1-58fb6559eff5.png)

After doing that, it is not possible to use the default launch site setting button until selecting one-time launch site to an open one:
![image](https://user-images.githubusercontent.com/603874/37245361-182415ae-2497-11e8-8d68-1206f60bf023.png)

Logs: 
[KSP.log](https://github.com/GER-Space/Kerbal-Konstructs/files/1799645/KSP.log)

**Comment by GER-Space** [comment]
the default button sets the currently actíve LaunchSie as default, not the selected one from the list.

**Comment by GER-Space** [comment]
you can veryfy this by pressing the use default button

**Comment by xilexio** [comment]
I see. Then I suggest renaming the button to "Use currently selected as default" or "Use current as default". Generally, it will probably still be a bit ambiguous, but I don't have anything better in mind at the moment.

**Comment by GER-Space** [comment]
You are right, I should change the behavior
