### ISSUE TITLE
Inconvenient fuel transfer from fuel tanks

### ISSUE THREAD

**Issue by xilexio** [GER-Space/Kerbal-Konstructs#72]
When the craft has a lot of fuel capacity, the user has to keep the button pressed for a really long time (imagine 10k+ fuel in a large aircraft when this pumps only around 25/s). It'd be better if the button had a toggle on/off option.
![image](https://user-images.githubusercontent.com/603874/37246121-94db2d92-24a3-11e8-8e86-059ee54f1a61.png)
Physical Warp does not affect this (so it can't help). Also, the fuel transfer seems slower than in previous versions. Transferring a few thousand units would be pretty boring from a gameplay perspective. I suggest either giving another +++ button or making the normal or physical warp affect the transfer rate.

**Comment by GER-Space** [comment]
its frame rate dependend.. I'll add a increment selector on the top. This was planned before, but i forgot about it...
I should also add this to the Storage facility.
