### ISSUE TITLE
Instant full funds in newly opened Office Estate

### ISSUE THREAD

**Issue by xilexio** [GER-Space/Kerbal-Konstructs#78]
When assigning kerbals to a previously closed Office Estate, the initial amount of funds produced by the office is set to maximum right away (assigned 12 kerbals). It was happening also in previous versions (1.2.\*.\*).
I don't see anything about this event in the logs.

**Comment by GER-Space** [comment]
I think I fixed it, but I'm not able to test this right now.

**Comment by GER-Space** [comment]
I tested it and cannot reprodice this issue anymore. I think one of the latest changes has fixed it
