### ISSUE TITLE
Crew dies when recovered from purchased KK facilities

### ISSUE THREAD

**Issue by Sundering0** [GER-Space/Kerbal-Konstructs#8]
I think I found a bug in career mode. Whenever I tried to recover a vessel from any purchased KK facility  (in my case i tried with Lodnie Isles and Polar Research Center from the KerbinSide package) the crew are not recovered and the parts refund is 0, not matter the facility has a recovery factor. The worse part is when I tried to launch another mission I noticed that the crew status is missing in action! I have checked and I'm pretty sure it is related to the recovery method used in Kerbal Konstruct.

![kerbal space program 11 15 2016 - 13 53 34 07](https://cloud.githubusercontent.com/assets/23483519/20317251/9f63e822-ab3b-11e6-8358-7354f280a633.png)
![kerbal space program 11 15 2016 - 13 54 42 08](https://cloud.githubusercontent.com/assets/23483519/20317259/a6e4d426-ab3b-11e6-86e4-a2b973395d5e.png)
![kerbal space program 11 15 2016 - 13 56 18 10](https://cloud.githubusercontent.com/assets/23483519/20317265/aac2b64e-ab3b-11e6-9f0c-5e6f446e1ede.png)

**Comment by GER-Space** [comment]
You found two bugs :-) 

1. Launch refund is not working
2. recovery is broken.

Still investigating.... there are a few issues here hidden :-(

**Comment by GER-Space** [comment]
intresting: I can recover the vessel with no problem from the trackingstation...

**Comment by GER-Space** [comment]
I put up a new prerelease, wich should fix the issues. 

https://github.com/GER-Space/Kerbal-Konstructs/releases/tag/0.9.8.3
