### ISSUE TITLE
Latest release seems to have broken the textures?

### ISSUE THREAD

**Issue by Galileo88** [GER-Space/Kerbal-Konstructs#81]
I was making some changes and realized the textures are no longer rendering on the models. Reverting back to 1.2.9.9 fixed the issue for me. Im just wondering if something changed, or is there something i need to change in the cfgs to make this work again? I haven't changed anything in almost a year in my GPP repo, and this is the first I have seen this happen.

[Here are some images](https://imgur.com/a/QtTbJ)

**Comment by GER-Space** [comment]
I might need you logfiles, because from my perspective it looks ok.

**Comment by Galileo88** [comment]
ok give me a sec

**Comment by Galileo88** [comment]
Disregard. starting a new game fixed it, but loading a save doesnt render the textures

**Comment by Galileo88** [comment]
But, I do not get the launch towers anymore. Ill post my logs anyway so you can see if anything is wrong

**Comment by Galileo88** [comment]
[https://www.dropbox.com/s/3b94xdg0224rx78/Logs.zip?dl=1](https://www.dropbox.com/s/3b94xdg0224rx78/Logs.zip?dl=1)

**Comment by GER-Space** [comment]
thank you I'll have a look

**Comment by Galileo88** [comment]
I should clarify, load THAT particular save wouldnt load the textures. Everything on that end seems ok
its just the launch towers now.

**Comment by GER-Space** [comment]
I sometimes get this. 
KK: Couldn't find body "Gael"

**Comment by Galileo88** [comment]
Damnit you are right as always. I missed a couple cfgs. Thanks!

**Comment by GER-Space** [comment]
any reason you reopended it?

**Comment by Galileo88** [comment]
Yeah just a quick question, I didnt know if you would see it if i didnt reopen it. Do you know if the statics cfgs are adjustable via MM cfg? I had to rename the home planet in GPP to Kerbin and let the display name change the name to Gael, but now Round Range and the default KSCUpgrades assets are now spawning. I can delete them via MM if thats possible.

**Comment by Galileo88** [comment]
It doesn't seem like it, unfortunately.

**Comment by Galileo88** [comment]
ok coolio thanks

**Comment by whale2** [comment]
Guys. sorry for jumping in, but MM can edit any .cfg file, regardless of is it a PART or no. Just checked.

**Comment by Galileo88** [comment]
It wont delete nodes in KK, though. 

@GER-Space I have reproduced the no texture issue. Make any change to an asset in game and exit. Load game and the assets are missing textures.
