### ISSUE TITLE
Reverting to space center error

### ISSUE THREAD

**Issue by Galileo88** [GER-Space/Kerbal-Konstructs#84]
When sitting on a KK launch site and you hit esc and click "Space Center" it takes you back to the default KSC but doesnt let you click on anything and the UI is not visible. I will add logs later if you need them.

**Comment by GER-Space** [comment]
Yes log files would be good, as I don't have that issue

**Comment by Galileo88** [comment]
I havent seen this issue since so i cannot post logs. I will reopen if it haooens again
