### ISSUE TITLE
1.4.x cannot launch from KK launch sites

### ISSUE THREAD

**Issue by Galileo88** [GER-Space/Kerbal-Konstructs#86]
In 1.4.x you cannot launch from KK launch sites; you are automatically put on the stock launch pad. This may be due to the dlc and and option top launch from extra stock sites. 

[HERE](https://www.dropbox.com/s/pft2ilgh4slzxwm/Logs%20and%20test%20launch%20sites.zip?dl=1) are the logs and some test launch sites. I tested these cfg in stock in 1.3.1, 1.4.1 and 1.4.2. They work fine in 1.3.1 but cant be used in 1.4.x.

As one other user reported, I was able to use the Round Range site once. After that, the same behavior as above continued.

**Comment by Skywalket** [comment]
Same happened to me. I found that re-selecting the launch site was a solution

**Comment by GER-Space** [comment]
Vacation is over. I was able to reproduce the issue and found a "not so messy" workaround. 
Honestly I'm suprised that this worked in KSP 1.3 without it.
