### ISSUE TITLE
Launching to water launch spawns on seabed 

### ISSUE THREAD

**Issue by SpannerMonkey** [GER-Space/Kerbal-Konstructs#88]
Launching to water launch spawns on seabed 
KSP 1.4 all versions
KK version Kerbal-Konstructs-1.4.0.1

Tried in totally clean KK squad build and busy build , same results

Replication install supplied  standalone ZIP 
Launch craft to any selected water launch site
(brace yourself for possibly large explosion)
Find surface craft spawning on sea bed.

For ref all but a couple of these items have been reset using the latest KK 1.4 preview
https://www.dropbox.com/s/dy8zexb18bsje5s/SM_WaterLaunch.zip?dl=0

**Comment by GER-Space** [comment]
This can only happen when KSP thinks the new vessel is loaded from cache and not newly launched. I think with 1.4 there had been some changes regarding the launch altitude of vessels and them dropping on the runway. I think this doesn't work when there is no collider under the spawnpoint.

Maybe I can set the vessels prosition to the right location for waterlaunch sites. 

I'll look into this tomorrow. now its too late.

**Comment by GER-Space** [comment]
not working with bigger vessels

**Comment by GER-Space** [comment]
I its now working on all vessels, they get pushed back to the surface before the physics kicks in
