### ISSUE TITLE
Add water support

### ISSUE THREAD

**Issue by GER-Space** [GER-Space/Kerbal-Konstructs#94]
some functional water above sea level would be nice.

**Comment by GER-Space** [comment]
kopernicus has some floating module, I need to see what they do and somhow not break this

**Comment by Ruedii** [comment]
This would be nice.

It's worth noting that KSP's current setup uses sea level to determine water.
Generally adding above sea level water involves adding an entirely separate water system for it (most of which can just be duplicated off of the stock routines.)

**Comment by GER-Space** [comment]
The easy part of adding the water physics I already finished. The only problem I had is the water shader when the Camera is under the new water.

**Comment by GER-Space** [comment]
the shader cannot be messed with. at least the physics is working.
