### ISSUE TITLE
Runway is permamently highlighted in green

### ISSUE THREAD

**Issue by m4ti140** [GER-Space/Kerbal-Konstructs#95]
After clicking on a KK base runway to return to hangar and launching a vessel from there, the runway remains highlighted in green indefinitely.

EDIT: Same applies to any other selectable object. It remains highlighted while in flight until I recover at that base and hover the mouse over that static.

**Comment by GER-Space** [comment]
this will be fixed in the next release. (at least for the launchSites) the facilities need a seperate fix

**Comment by GER-Space** [comment]
this is fixed
