### ISSUE TITLE
Map icons are black/blank

### ISSUE THREAD

**Issue by doomsteam** [GER-Space/Kerbal-Konstructs#97]
so i installed kerbal konstructs along with kerbin-side, and when i went to the tracking station the icons for all the bases (except ksc2) were all blank!

https://gyazo.com/9cb2fdda4f106a624df9ed905dc0375d

so, any idea on whats happening? or did i forget to install something?

**Comment by doomsteam** [comment]
Oh, and the stock 1.4 ksc image is blocked by the blank images too.

**Comment by GER-Space** [comment]
Maybe it is an issue with some texture compression algorithms. These tend to kill small files.
