### ISSUE TITLE
Space character (%20) in file name breaks ModuleManager cache

### ISSUE THREAD

**Issue by ghost** [GER-Space/Kerbal-Konstructs#98]
Looks like a space character in the file name prevents ModuleManager from properly applying its cache, even though the hash is clearly unchanged:

```
[LOG 14:27:34.821] [ModuleManager] Checking Cache
[LOG 14:27:35.256] [ModuleManager] SHA generated in 0.432s
[LOG 14:27:35.256] [ModuleManager]       SHA = BB-97-44-62-55-BF-1A-9A-DB-5B-F2-38-9B-D5-88-CD-A6-2F-0A-A9-63-4A-1F-24-65-F7-26-A0-E5-3A-57-65
[LOG 14:27:35.657] [ModuleManager] Changes :
Added   : KerbalKonstructs/FreeStatics/KKflagDemo/AutoGrasDemo .cfg
Deleted : KerbalKonstructs/FreeStatics/KKflagDemo/AutoGrasDemo.cfg

[LOG 14:27:35.657] [ModuleManager] Cache SHA = BB-97-44-62-55-BF-1A-9A-DB-5B-F2-38-9B-D5-88-CD-A6-2F-0A-A9-63-4A-1F-24-65-F7-26-A0-E5-3A-57-65
[LOG 14:27:35.657] [ModuleManager] useCache = False
```

Simply renaming the file manually allows MM to use its cache again.
Ultimately it would need to be resolved within MM, but a simple name change would work around the issue for the time being.

https://github.com/GER-Space/Kerbal-Konstructs/blob/36ad6c2b508e16f7fbd90cdf5428cae02202f917/GameData/KerbalKonstructs/FreeStatics/KKflagDemo/AutoGrasDemo%20.cfg

---
cf. sarbian/ModuleManager/issues/121

**Comment by GER-Space** [comment]
this will be fixed in the next release

**Comment by GER-Space** [comment]
this is fixed on my side and released
