### ISSUE TITLE
Launch from space center

### ISSUE THREAD

**Issue by alex-dev** [GER-Space/Kerbal-Konstructs#99]
When trying to lauch from any KK lauch site through the stock lauch window, it will crash and go back to space center.

> [LOG 12:40:17.343] Mark I Pod loaded!
> [EXC 12:40:19.971] ArgumentNullException: Kojave Sands Launch Pad is not a valid Space Center Facility name!
> Parameter name: pSystemFacility
> 	EditorEnumExtensions.GetFacility (.SpaceCenterFacility pSystemFacility)
> 	FlightDriver.setStartupNewVessel ()
> 	UnityEngine.Debug:LogException(Exception)
> 	FlightDriver:setStartupNewVessel()
> 	FlightDriver:Start()

Launching from VAB/SPH is fine.

Here is the [whole thing](https://github.com/GER-Space/Kerbal-Konstructs/files/2065188/SceneChanges.log), from scene change to scene change.
Here is the [KSP.log](https://github.com/GER-Space/Kerbal-Konstructs/files/2065189/KSP.log).

**Comment by GER-Space** [comment]
This is now fixed in the 1.4.5.31 release
